---
deployment:
  tasks:
    - export DEPLOYPATH=/home/theeiorh/public_html/
    - /bin/cp -R *.html *.css *.js .htaccess $DEPLOYPATH
    - /bin/cp -R empire $DEPLOYPATH
    - /bin/cp -R logos $DEPLOYPATH
